### PR TITLE
feat: make ssh public key optional

### LINKED ISSUE #446: Possibility to create cluster without Admin SSH Key
Since it is possible to create a kops [cluster](https://kops.sigs.k8s.io/cli/kops_create_cluster/) without specifying an admin ssh key it would be nice to be able to do that using the provider as well.

Connecting to the instances is still possible with for example [ec2-instance-connect](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html#connect-options)

### PR DESCRIPTION
**Pull request by eddycharly**
This PR makes ssh public key optional.

### CODE REVIEW

**Comment by peter-svensson** [comment]
I can test it tomorrow

**Comment by eddycharly** [comment]
> I can test it tomorrow

It would be great 🙏 
I'm going to merge and release another alpha.

**Comment by peter-svensson** [comment]
Seems to be working fine.
Tried updating an existing cluster and created a new one.

**Comment by eddycharly** [comment]
Thanks for trying it out 🎉

**Pull request merged**
