### PR TITLE
Fix: manage_storage_classes should be nullable

### LINKED ISSUE #1043: manageStorageClasses not populated when "false" and does not apply
When setting `cloud_config.manage_storage_classes = false` this does not populate `cloudConfig.manageStorageClasses` leaving it to the default value of `true` when the [value is nil](https://github.com/kubernetes/kops/blob/d31d498af3aa2299c09bbcdc61fc6dac3f7749ff/pkg/model/components/cloudconfiguration.go#L43)
As a result, the kops default storageclass is created, creating conflicts with a custom default storageclass, preventing PVCs without explicit storage class to be created, until the kops default class is manually deleted

* **manage_storage_classes: true**
```
cloud_config {
    manage_storage_classes = true
  }
```
```
kops get cluster -o json | jq -r .spec.cloudConfig
{
  "manageStorageClasses": true
}
```
* **manage_storage_classes: false**
```
cloud_config {
    manage_storage_classes = false
  }
```
```
kops get cluster -o json | jq -r .spec.cloudConfig
{}
```

* Version: 1.25.3

### PR DESCRIPTION
**Pull request by kuldazbraslav**
Fixes #1043 

Kops field `cluster.spec.cloudConfig.manageStorageClasses` behaves as true if not set. Thus it should be nullable.

### CODE REVIEW

**Comment by eddycharly** [comment]
Thanks !

**Review by eddycharly — APPROVED** [review]

**Comment by kuldazbraslav** [comment]
@eddycharly  Any chance this bugfix could make it to v1.25 too?

**Comment by eddycharly** [comment]
Let's try... so much things changed in kOps between 1.25 and 1.26 🤷

**Pull request merged**
