### PR TITLE
feat: add kops 1.25 support

### PR DESCRIPTION
**Pull request by eddycharly**
This PR is to support kOps 1.25

### CODE REVIEW

**Comment by argoyle** [comment]
Would be happy to do that 😄

**Comment by eddycharly** [comment]
> Would be happy to do that smile

Fixing a little issue with codegen (`hosted_zone_i_ds`) and I'll cut an alpha.
Thanks!

**Comment by argoyle** [comment]
Got the notification from Github, will test during the day and get back to you.

**Comment by argoyle** [comment]
Seems to work fine. Created a cluster using the last non-alpha-release and K8S 1.24.5, upgrade to the alpha-release went fine and another upgrade to K8S 1.25.0 is rolling as we speak and seems to work fine as well.

**Comment by eddycharly** [comment]
Thank you so much for taking the time to test it!
I will probably release it today or tomorrow.

**Pull request merged**
