### PR TITLE
feat: add kops 1.24 support

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds kOps 1.24 support.

### CODE REVIEW

**Comment by eddycharly** [comment]
Anyone would be ok to test this ?
cc @argoyle ?

**Comment by argoyle** [comment]
Of course, will test it tomorrow

**Comment by eddycharly** [comment]
> Of course, will test it tomorrow

Thanks, I'll cut an alpha release tonight.

**Comment by eddycharly** [comment]
Just released `v1.24.0-alpha.1`.

**Comment by eddycharly** [comment]
@argoyle any chance you could give this a try ?

**Comment by argoyle** [comment]
Sorry, other stuff got in the way yesterday and today was busy as well. Will hopefully find some time tomorrow.

**Comment by argoyle** [comment]
Ok, tried it out now. Created a cluster using previous version of provider and tried to upgrade it and got this:
```
╷
│ Error: Plugin did not respond
│
│   with module.k8s.kops_cluster.k8s,
│   on ../../Opzkit/terraform-aws-k8s/k8s.tf line 20, in resource "kops_cluster" "k8s":
│   20: resource "kops_cluster" "k8s" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-kops_v1.24.0-alpha.1 plugin:

panic: interface conversion: interface {} is string, not []interface {}

goroutine 29 [running]:
github.com/eddycharly/terraform-provider-kops/pkg/schemas/kops.ExpandResourceClusterSpec.func4.1(...)
	github.com/eddycharly/terraform-provider-kops/pkg/schemas/kops/Resource_ClusterSpec.generated.go:42
github.com/eddycharly/terraform-provider-kops/pkg/schemas/kops.ExpandResourceClusterSpec.func4({0x106787840?, 0x14000626200?})
	github.com/eddycharly/terraform-provider-kops/pkg/schemas/kops/Resource_ClusterSpec.generated.go:46 +0x110
github.com/eddycharly/terraform-provider-kops/pkg/schemas/kops.ExpandResourceClusterSpec(_)
	github.com/eddycharly/terraform-provider-kops/pkg/schemas/kops/Resource_ClusterSpec.generated.go:47 +0x150
github.com/eddycharly/terraform-provider-kops/pkg/schemas/resources.ExpandResourceCluster.func1(...)
	github.com/eddycharly/terraform-provider-kops/pkg/schemas/resources/Resource_Cluster.generated.go:143
github.com/eddycharly/terraform-provider-kops/pkg/schemas/resources.ExpandResourceCluster(_)
	github.com/eddycharly/terraform-provider-kops/pkg/schemas/resources/Resource_Cluster.generated.go:144 +0x48
github.com/eddycharly/terraform-provider-kops/pkg/schemas/resources.ResourceCluster.func3({0x0?, 0x0?}, 0x0?, {0x0?, 0x0?})
	github.com/eddycharly/terraform-provider-kops/pkg/schemas/resources/Resource_Cluster.generated.go:119 +0x30
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).upgradeJSONState(0x140006d0258, {0x10751c138, 0x14000b18990}, 0xd?, 0x105acfa10?, 0x14?)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:449 +0xa4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).UpgradeResourceState(0x140006d0258, {0x10751c138?, 0x14000b18870?}, 0x14000722a60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.20.0/helper/schema/grpc_provider.go:325 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).UpgradeResourceState(0x140007ac0a0, {0x10751c138?, 0x14000b07b30?}, 0x14000d32a50)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:716 +0x224
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_UpgradeResourceState_Handler({0x1072ca3a0?, 0x140007ac0a0}, {0x10751c138, 0x14000b07b30}, 0x14000e23b20, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:313 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000392780, {0x107524630, 0x14000509520}, 0x140009a8900, 0x1400053f380, 0x109931100, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0x9d8
google.golang.org/grpc.(*Server).handleStream(0x14000392780, {0x107524630, 0x14000509520}, 0x140009a8900, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x298

Error: The terraform-provider-kops_v1.24.0-alpha.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Will try a fresh cluster directly with 1.24.0-alpha.1 as well.

**Comment by eddycharly** [comment]
Did you change the `cloud_provider` type ?

**Comment by eddycharly** [comment]
Before:
`cloud_provider = "aws"`

After:
```
  cloud_provider {
    aws {}
  }
```

**Comment by argoyle** [comment]
Yes, I changed that. Creating a fresh cluster gives this for each of the instance groups:
```
│ Error: spec.image: Forbidden: image must be specified.
│
│   with module.k8s.kops_instance_group.masters["a"],
│   on ../../Opzkit/terraform-aws-k8s/k8s.tf line 196, in resource "kops_instance_group" "masters":
│  196: resource "kops_instance_group" "masters" {
│
```

**Comment by eddycharly** [comment]
Looks like the error comes from kOps, it's still optional in the provider.
Let me check id something changed on the kOps side.

**Comment by eddycharly** [comment]
I reproduced the issue, fixing. kOps has stricter validation.
This should have been catched by integration tests, i definitely need to run those tests in the CI.

**Comment by eddycharly** [comment]
`v1.24.0-alpha.2` is being built, hopefully it will fix the issue :crossed_fingers:

**Comment by argoyle** [comment]
Fresh cluster was better now. First apply failed after 20 minutes (my validate and rolling update timeout for updater), second apply showed this change for each instance group:
```
  # module.k8s.kops_instance_group.masters["a"] will be updated in-place
  ~ resource "kops_instance_group" "masters" {
        id                           = "k8s.xxx.se/master-eu-north-1a"
      - manager                      = "CloudGroup" -> null
        name                         = "master-eu-north-1a"
      ~ revision                     = 1 -> 2
        # (28 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```
Had to edit the cluster autoscaler deployment to allow for spot-workers (since that is our regular setup in the Terraform modules we use) to get the cluster to become valid.

Will try an upgrade now.

**Comment by argoyle** [comment]
Upgrade still fails with the first error I posted above (https://github.com/eddycharly/terraform-provider-kops/pull/657#issuecomment-1206359001)

**Comment by eddycharly** [comment]
> Fresh cluster was better now. First apply failed after 20 minutes (my validate and rolling update timeout for updater), second apply showed this change for each instance group:

This is improving !
`manager` is new in 1.24, I needed to mark it as computed, fixing...

> Had to edit the cluster autoscaler deployment to allow for spot-workers (since that is our regular setup in the Terraform modules we use) to get the cluster to become valid.

Was this working with 1.23 without editing the cluster autoscaler deployment ?

> Upgrade still fails with the first error I posted above (https://github.com/eddycharly/terraform-provider-kops/pull/657#issuecomment-1206359001)

Humm, this happens because of the change in `cloud_porivder`, I need to find a way to migrate it correctly.

**Comment by argoyle** [comment]
Cool, cluster autoscaler worked fine with spot instances in 1.23.x. It's a change in kOps that I've known about for a while but forgot about anyway. 😄

**Comment by eddycharly** [comment]
What did you have to change in the deployment to make autoscaler work ?

**Comment by eddycharly** [comment]
Ok, `v1.24.0-alpha.3` is being built, it should fix the `manager` and upgrade issues :crossed_fingers: 

Let me know how I can help with the autoscaler issue.

**Comment by argoyle** [comment]
Running an upgrade now and it seems to run as expected now with alpha 3. Good job!

Regarding the autoscaler I just removed the affinity-block.

**Comment by argoyle** [comment]
It's probably not a good idea to run the cluster on only spot-instances so we should probably look into reserved instances (at least as a base).

**Comment by eddycharly** [comment]
I’ll check but we should be able to use spot instances if we want to.

**Pull request merged**
