### PR TITLE
fix: comparison operator when sorting keys

### PR DESCRIPTION
**Pull request by eddycharly**
This PR fixes comparison operator when sorting keys.

### CODE REVIEW

**Comment by eddycharly** [comment]
cc @argoyle

**Review by argoyle — APPROVED** [review]
Hmmm, no changes to the template? Or did I just forget to add the generated files in my PR?

**Comment by eddycharly** [comment]
Not sure why, I thought the generated code was checked in the CI 🤔 
I will add that.

**Comment by eddycharly** [comment]
@argoyle `v1.25.2-alpha.1` is being built. Let me know if it fixes your issues 🤞

**Comment by argoyle** [comment]
Tested now. Worked exactly as expected! 🎉 🍾 Thanks!

**Comment by eddycharly** [comment]
Awesome, thanks !
I will cut a release today :)

**Pull request merged**
